# Read before maintaining:
# Each .YML Action in .github/workflows shares its base filename with a python file in EasyDockerFile/Resources/Maintenance
name: Update Fedora Image Versions

on:
  schedule:
    # Runs on every Tuesday in April and October to match the release cycle
    # Per: https://docs.fedoraproject.org/en-US/releases/lifecycle/#_schedule_methodology
    - cron: '0 0 * 4,10 2'
  workflow_dispatch: # Allows access to the task through the UI (please do not remove if contributing)

jobs:
  update-xml:
    runs-on: ubuntu-latest
    env:
      IMAGES_XML_PATH: "src/EasyDockerFile/Resources/Images.xml"
      SCRIPT_PATH: "src/EasyDockerFile/Resources/Maintenance/fedora-version-update.py"
    steps:
      - name: Entering repository root
        uses: actions/checkout@v4
        with:
          path: '.' # This fixes issues with checking out to a subdirectory instead of the root dir

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installing Dependencies
        run: pip install requests

      - name: Updating Fedora release versions
        run: python ${{ env.SCRIPT_PATH }}

      - name: Commiting and pushing changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update Fedora release versions [Runner Action]"
          file_pattern: "${{ env.IMAGES_XML_PATH }}"
